import 'package:flutter/material.dart';
import 'package:home_assist/features/bookings/domain/entities/booking.dart';

final bookings = [
  Booking(
    id: 'BK1001',
    serviceId: 'S1',
    serviceName: 'Electrical Wiring Repair',
    providerName: 'Ravi Kumar',
    amount: 299,
    bookingDate: DateTime(2026, 6, 25),
    bookingTime: const TimeOfDay(hour: 10, minute: 30),
    address: '12 MG Road, Bangalore',
    status: 'Upcoming',
  ),
  Booking(
    id: 'BK1002',
    serviceId: 'S5',
    serviceName: 'Deep Home Cleaning',
    providerName: 'Arjun Patel',
    amount: 799,
    bookingDate: DateTime(2026, 6, 28),
    bookingTime: const TimeOfDay(hour: 9, minute: 0),
    address: '45 Residency Road, Hyderabad',
    status: 'Confirmed',
  ),
  Booking(
    id: 'BK1003',
    serviceId: 'S7',
    serviceName: 'Wall Painting',
    providerName: 'Rahul Sharma',
    amount: 1499,
    bookingDate: DateTime(2026, 6, 20),
    bookingTime: const TimeOfDay(hour: 14, minute: 0),
    address: '78 Banjara Hills, Hyderabad',
    status: 'Completed',
  ),
  Booking(
    id: 'BK1004',
    serviceId: 'S3',
    serviceName: 'Pipe Leak Repair',
    providerName: 'Arjun Patel',
    amount: 349,
    bookingDate: DateTime(2026, 6, 22),
    bookingTime: const TimeOfDay(hour: 16, minute: 30),
    address: '22 Jubilee Hills, Hyderabad',
    status: 'Completed',
  ),
  Booking(
    id: 'BK1005',
    serviceId: 'S11',
    serviceName: 'Furniture Assembly',
    providerName: 'Vikram Singh',
    amount: 399,
    bookingDate: DateTime(2026, 7, 1),
    bookingTime: const TimeOfDay(hour: 11, minute: 0),
    address: '9 Park Street, Chennai',
    status: 'Upcoming',
  ),
];